#! /usr/bin/make -f

# quay.io/operator-framework/operator-sdk@sha256:91fecfad7a7ac3e8a276621548971f0f7fec43e454b1163372fa29b85cab1106
operator_sdk_image=operator-sdk
operator_sdk_namespace=operator-framework
operator_sdk_tag=v1.25.1
operator_sdk_name=$(operator_sdk_namespace)-$(operator_sdk_image)-$(operator_sdk_tag)-operator_sdk
operator_sdk_registry=quay.io
#operator_sdk_scm_prefix=git::https://github.com/ben-obrien
#operator_sdk_scm_ref=
